### ISSUE TITLE
Do we need the Reject function?

### ISSUE THREAD

**Issue by Fenny** [yannickl/AwaitKit#34]
Do we need the reject callback inside a promise?
The below code seems to be working out for me, it catches any error and instead of rejecting it returns null in the resolve function.
Is this bad code, if so why?

```javascript
function fecthDB() {
	return new Promise((resolve, reject) => {
		try {
			db.query('SELECT * FROM users' (err, result) => {
				if (err || !results) {
					return resolve(null)
				}
				resolve(result)
			})
		} catch (e) {
			resolve(null)
		}
	})
}

function async getUsers() {
	var users = await fecthDB()
	if (!users) { // error handling
		return console.log('error')
	}
	console.log(users) // got users
}
```

**Comment by yannickl** [comment]
Sorry for the very late. There is no perfect answer to your question. If this is the intended behaviour it can work. But in a semantic point of view this is better to manage the error and the "empty" states differently.

In the *catch* block you should call `reject` instead of `resolve` because if there is an issue with the db call you may want manage your workflow app differently.
